[s3]
bucket = "power-inspection"
prefix = "ParkSokury.TP3(225)/"        # можно оставить пустым "", если корень
region = "eu-central-1"
aws_access_key_id = "3kPuXsWRjGDwChHZzhRV4b"
aws_secret_access_key = "dk31mZtvCMh9X6cJfUmh6B1XdZzd2Kn9E5b533GwPVZx"
