[s3]
bucket = "power-inspection"
prefix = "ParkSokury.TP3(225)/"           # "" если в корне
region = "eu-central-1"       # опционально, если endpoint_url задан — можно оставить как есть
endpoint_url = "https://hb.ru-msk.vkcloud-storage.ru"   # <-- ВАЖНО для S3-совместимых
aws_access_key_id = "3kPuXsWRjGDwChHZzhRV4b"
aws_secret_access_key = "dk31mZtvCMh9X6cJfUmh6B1XdZzd2Kn9E5b533GwPVZx"
path_style = true             # true для MinIO/Selectel/старых S3; false по умолчанию
signature_version = "s3v4"    # опционально; если провайдер требует s3v4
# при необходимости можно переопределить шаблон имени файла:
# filename_regex = "(?i).*-(?P<Y>\\d{4})\\.(?P<m>\\d{2})\\.(?P<d>\\d{2})-(?P<H>\\d{2})\\.(?P<M>\\d{2})\\.csv$"
